---

- name: Create the infrastructure
  block:

    - name: Create the Vault host Droplet
      digital_ocean_droplet:
        state: present
        name: "{{ vaulthost.name }}"
        unique_name: "{{ vaulthost.unique_name }}"
        image: "{{ vaulthost.image }}"
        size: "{{ vaulthost.size }}"
        region: "{{ vaulthost.region }}"
        monitoring: "{{ vaulthost.monitoring }}"
        private_networking: "{{ vaulthost.private_networking }}"
        ssh_keys: "{{ vaulthost.ssh_keys }}"
        oauth_token: "{{ vaulthost.oauth_token }}"
      register: vaulthost_droplet

    - name: Show the Vault host's IP information
      debug:
        msg: |
          ssh root@{{ vaulthost_droplet.data.ip_address }}
          ssh root@{{ vaulthost_droplet.data.private_ipv4_address }}

- name: Configure the application # Following: https://learn.hashicorp.com/tutorials/vault/getting-started-install
  block:

    - name: Add the APT Key for HashiCorp
      apt_key:
        state: present
        url: https://apt.releases.hashicorp.com/gpg

    - name: Install the APT Repository for HashiCorp
      apt_repository:
        state: present
        repo: deb [arch=amd64] https://apt.releases.hashicorp.com bionic main

    - name: Install HashiCorp Vault
      apt:
        state: present
        name: vault
        update_cache: yes

    # - name: Start and enable HashiCorp Vault
    #   service:
    #     name: vault
    #     state: started
    #     enabled: yes

  delegate_to: root@{{ vaulthost_droplet.data.ip_address }}
  connection: ssh
